### ISSUE TITLE
Error:listen EADDRNOTAVAIL 

### ISSUE THREAD

**Issue by YangLuYang** [joyqi/socket-pipe#2]
```
C:\Users\Administrator>socket-pipe -l 123.206.58.202@18888 -r 123.206.58.202@808
0 -t tserver
Piping 123.206.58.202@18888 to 123.206.58.202@8080 via tserver
{ Error: listen EADDRNOTAVAIL 123.206.58.202:18888
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '123.206.58.202',
  port: 18888 }
{ Error: listen EADDRNOTAVAIL 123.206.58.202:8080
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '123.206.58.202',
  port: 8080 }

```
服务器用的是腾讯云的。

**Comment by joyqi** [comment]
执行这条命令的服务器ip地址是123.206.58.202吗，有的云服务用的是NAT内网映射，所以本地实际上是一个局域网地址，看一下当前机器的实际IP地址

**Comment by YangLuYang** [comment]
可以了，用ipconfig/all 看了实际的ipv4地址，然后把公网ip换成了实际的ip，tcp能正常映射了。
8080能正常映射，映射端口换成80后出现下面的问题。

```
C:\Users\Administrator>socket-pipe -l 10.141.9.95@18888 -r 10.141.9.95@80 -t tserver
Piping 10.141.9.95@18888 to 10.141.9.95@80 via tserver
{ Error: listen EACCES 10.141.9.95:80
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '10.141.9.95',
  port: 80 }
connected 122.206.190.62:10644

```

**Comment by joyqi** [comment]
应该是主机对80端口的权限做了限制，我对windows的权限不熟悉，我猜可以试试在管理员模式下运行试试

**Comment by YangLuYang** [comment]
Centos下测试成功
